### ISSUE TITLE
obs-fb-live-comments.web.app doesn't show comment now

### ISSUE THREAD

**Issue by dhow** [xxRockOnxx/obs-fb-live-comments#3]
Hi,

The https://obs-fb-live-comments.web.app/ doesn't show comment anymore, instead it's showing this. How do I fix this? 

![capture_20200416_211642_002](https://user-images.githubusercontent.com/3618837/79455288-9c256e00-8027-11ea-829b-37cae6ce31c5.jpg)

Thanks!

**Comment by lemuelflores** [comment]
That's the new update. I have to put it up so that Facebook Review team can see and try it for themselves. Can you try https://obs-fb-live-comments.web.app/live?access_token=123&video_id=456 if it'll work?

**Comment by lemuelflores** [comment]
See #2
