### ISSUE TITLE
Getting error in console

### ISSUE THREAD

**Issue by raymondvill** [xxRockOnxx/obs-fb-live-comments#4]
![image](https://user-images.githubusercontent.com/60288698/87444731-bf14ed80-c629-11ea-95e8-1f3167d7a7e8.png)

Help?

**Comment by lemuelflores** [comment]
Are you trying to use it in a page and not on a personal account?
Im not sure if that's going to work cause I haven't tried it and I believe there are tools available already?
Maybe this: https://streamelements.com? I haven't tried that one cause I don't have a page but that might have what you need.

But anyway, in case you still want to try:
1. You aren't logged in
2. Refresh the page. It could be you have pasted the code more than once (re-declaring the variable `ID` again) or the page already has a variable called `ID`. If after refreshing and pasting it just once still throws an error, replace every `ID` you see to something like `ID2`. Do not replace the small ones i.e `id`

**Comment by lemuelflores** [comment]
Closing because OP didn't reply and new code is available that might not cause this issue anymore.
