### ISSUE TITLE
Browser source opened in debugger just shows a blank screen

### ISSUE THREAD

**Issue by salvadornico** [xxRockOnxx/obs-fb-live-comments#5]
Hi there, I just tried out your technique today but unfortunately, when I got the the step where you open the browser source in OBS debugging all I got was a white screen with the normal Facebook warning message in the console. Looks like there might be some new code on the page preventing this?

![image](https://user-images.githubusercontent.com/25360297/104102691-fd3d5200-52d8-11eb-88cf-cd38b32c20aa.png)
This link is from a page because I pulled it up just to make the screenhot, but it's the same for a personal profile

![image](https://user-images.githubusercontent.com/25360297/104102813-a126fd80-52d9-11eb-8d62-950c2876b905.png)
This is how it appears in the OBS preview

**Comment by lemuelflores** [comment]
I totally forgot about this one. I just want to say I still want to keep this method somewhat alive as long as i can so stay tuned. I'll check it out as soon as i can.

**Comment by lemuelflores** [comment]
Closing because this issue seems to not happen anymore ime. An updated code is also available.
